apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ include "webui.fullname" . }}-webui'
  labels:
    {{- include "webui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: '{{ include "webui.name" . }}-webui'
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: '{{ include "webui.name" . }}-webui'
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.pullsecret}}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
         
          command: ["/bin/sh"]
          args: ["-c", "cd webconsole && ./server"]
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          volumeMounts:
            - name: webui-configuration
              mountPath: /free5gc/config/
      volumes:
        - name: webui-configuration
          configMap:
            defaultMode: 420
            name: '{{ include "webui.fullname" . }}-cfgmap'
