apiVersion: v1
kind: Service
metadata:
  name: '{{ include "webui.name" . }}-webui'
  labels:
    {{- include "webui.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.webui.service.type }}
  ports:
    - port: {{ .Values.webui.service.port }}
      targetPort: 5000
      nodePort: {{ .Values.webui.service.nodeport }}
  selector:
    app.kubernetes.io/name: '{{ include "webui.name" . }}-webui'
    app.kubernetes.io/instance: {{ .Release.Name }}
