apiVersion: v1
kind: ConfigMap
metadata:
  name:  '{{ include "webui.fullname" . }}-cfgmap'
  labels:
    name: webui-config
  namespace: {{ .Release.Namespace }}
data:
  webuicfg.conf: |-
    info:
      version: 1.0.0
      description: WebUI initial local configuration

    configuration:
      mongodb:
        name: free5gc
        url: mongodb://{{ .Values.mongodb.url}}:{{ .Values.mongodb.port}}
 
