apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "udr.fullname" . }}-udr
  labels:
    {{- include "udr.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "udr.name" . }}-udr
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "udr.name" . }}-udr
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.pullsecret}}
      hostNetwork: {{ .Values.hostnetwork}}
      containers:
        - name: {{ .Chart.Name }}
          image: '{{ .Values.image.name }}:{{ .Values.image.tag }}'
          imagePullPolicy: {{ .Values.image.pullPolicy }}
         
          command: ["/bin/sh"]
          args: ["-c", "./udr"]
          ports:
            - name: http-udr
              containerPort: {{.Values.config.udr.nudrport}}
              protocol: TCP
          volumeMounts:
            - name: udr-configuration
              mountPath: /free5gc/config/
      volumes:
        - name: udr-configuration
          configMap:
            defaultMode: 420
            name: {{ include "udr.fullname" . }}-cfgmap
