kind: Service
apiVersion: v1
metadata:
  name: {{ include "udr.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "udr.name" . }}-udr
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: {{ .Values.config.udr.nudrport }}
    targetPort: http-udr
