apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mongodb.name" . }}-cfgmap
  labels:
    app: database
  namespace: {{ .Release.Namespace }}
data:
  mongo.conf: |
    storage:
      dbPath: /data/db
