apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb.name" . }}-svc
  labels:
    app: database
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  selector:
    app: database
