apiVersion: v1
kind: ConfigMap
metadata:
  name:  '{{ include "udm.fullname" . }}-cfgmap'
  labels:
    name: udm-config
  namespace: {{ .Release.Namespace }}
data:
  udmcfg.conf: |-
    info:
      version: 1.0.0
      description: UDM initial local configuration

    configuration:
      serviceNameList:
        - nudm-ueau
      sbi:
        scheme: {{ .Values.config.udm.nudmscheme }}
        bindingIPv4: {{ .Values.config.udm.bindingIPv4 }}
        registerIPv4: udm.{{ .Release.Namespace }}.svc.cluster.local 
        port: {{ .Values.config.nudmport }}
        tls:
          log: free5gc/udmsslkey.log
          pem: free5gc/support/TLS/udm.pem
          key: free5gc/support/TLS/udm.key
  
      udrclient:
        scheme: {{ .Values.config.udr.scheme }}
        ipv4Addr: {{ .Values.config.udr.udrsvcname }}
        port: {{ .Values.config.udr.port }}

      nrfclient:
        scheme: http
        ipv4Addr: nrf.{{ .Release.Namespace }}.svc.cluster.local
        port: 29510
      nrfUri: http://nrf.{{ .Release.Namespace }}.svc.cluster.local:29510

      keys:
        udmProfileAHNPublicKey: 5a8d38864820197c3394b92613b20b91633cbd897119273bf8e4a6f4eec0a650
        udmProfileAHNPrivateKey: c53c22208b61860b06c62e5406a7b330c2b577aa5558981510d128247d38bd1d
        udmProfileBHNPublicKey: 0472DA71976234CE833A6907425867B82E074D44EF907DFB4B3E21C1C2256EBCD15A7DED52FCBB097A4ED250E036C7B9C8C7004C4EEDC4F068CD7BF8D3F900E3B4
        udmProfileBHNPrivateKey: F1AB1074477EBCC7F554EA1C5FC368B1616730155E0041AC447D6301975FECDA
  
    
 
