apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ include "nrf.fullname" . }}-nrf'
  labels:
    {{- include "nrf.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: '{{ include "nrf.name" . }}-nrf'
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: '{{ include "nrf.name" . }}-nrf'
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.pullsecret}}
      hostNetwork: {{ .Values.hostnetwork}}
      containers:
        - name: {{ .Chart.Name }}
          image: '{{ .Values.image.name }}:{{ .Values.image.tag }}'
          imagePullPolicy: {{ .Values.image.pullPolicy }}
         
          command: ["/bin/sh"]
          args: ["-c", "./nrf"]
          ports:
            - name: http-nrf
              containerPort: {{.Values.config.port}}
              protocol: TCP
          volumeMounts:
            - name: nrf-configuration
              mountPath: /free5gc/config/
      volumes:
        - name: nrf-configuration
          configMap:
            defaultMode: 420
            name: '{{ include "nrf.fullname" . }}-cfgmap'
