kind: Service
apiVersion: v1
metadata:
  name: nrf
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: '{{ include "nrf.name" . }}-nrf'
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: 29510
    targetPort: http-nrf
    
