# Default values for udm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
repository: 
image:
  name: webconsole
  tag: 0.0.1
  pullPolicy: IfNotPresent

webui:
  service:
    type: NodePort
    nodeport: 32000
    port: 5000
mongodb:
  url: mongodb-standalone-0.mongodb-svc
  port: 27017



# registry pull  secret
pullsecret: regitrypullsecret
nameOverride: ""
fullnameOverride: ""


