kind: Service
apiVersion: v1
metadata:
  name: ausf
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: '{{ include "ausf.name" . }}-ausf'
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: 29509
    targetPort: http-ausf
    
